# Generated by Django 6.0.4 on 2026-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
