# Generated by Django 6.0.4 on 2026-08-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Defective Product', 'Defective Product'), ('Wrong Product', 'Wrong Product'), ('Damaged Product', 'Damaged Product'), ('Size Issue', 'Size Issue'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Product Received', 'Product Received'), ('Refund Processing', 'Refund Processing'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Requested', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('product_received_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='app1.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='app1.users')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='app1.order')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='app1.returnrequest')),
            ],
        ),
    ]
