# Generated by Django 6.0.4 on 2026-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
