# Generated by Django 6.0.4 on 2026-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_contactmessage_admin_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ORDER', 'Order'), ('CANCELLED_ORDER', 'Cancelled Order'), ('REVIEW', 'Review'), ('CONTACT', 'Contact')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
