# Generated by Django 6.0.4 on 2026-09-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('CANCELLED_ORDER', 'Cancelled Order'), ('REVIEW', 'Review'), ('CONTACT', 'Contact'), ('RETURN', 'Return')], max_length=30),
        ),
    ]
